// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Transfers.Infrastructure.Persistence;

#nullable disable

namespace Transfers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TransfersDbContext))]
    partial class TransfersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Transfers.Domain.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("OverdraftLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Accounts", t =>
                        {
                            t.HasCheckConstraint("CK_Accounts_Balance_WithinOverdraft", "[Balance] >= -[OverdraftLimit]");

                            t.HasCheckConstraint("CK_Accounts_OverdraftLimit_NonNegative", "[OverdraftLimit] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 5000m,
                            HolderName = "João",
                            OverdraftLimit = 1000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 2000m,
                            HolderName = "Maria",
                            OverdraftLimit = 500m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 500m,
                            HolderName = "Carlos",
                            OverdraftLimit = 1000m,
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 5000m,
                            HolderName = "Conta Bloqueada",
                            OverdraftLimit = 1000m,
                            Status = "Blocked"
                        });
                });

            modelBuilder.Entity("Transfers.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DestinationAccountId")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTimeOffset?>("ScheduledFor")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SourceAccountId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Transfers_IdempotencyKey")
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("DestinationAccountId", "CreatedAt");

                    b.HasIndex("SourceAccountId", "CreatedAt");

                    b.HasIndex("Status", "ScheduledFor");

                    b.ToTable("Transfers", t =>
                        {
                            t.HasCheckConstraint("CK_Transfers_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Transfers_DifferentAccounts", "[SourceAccountId] <> [DestinationAccountId]");
                        });
                });

            modelBuilder.Entity("Transfers.Domain.Transfers.TransferAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("bit");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.HasIndex("AccountId", "AttemptedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("AccountId", "AttemptedAt"), new[] { "Amount", "Succeeded" });

                    b.ToTable("TransferAttempts");
                });

            modelBuilder.Entity("Transfers.Domain.Transfers.Transfer", b =>
                {
                    b.HasOne("Transfers.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("DestinationAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transfers.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("SourceAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Transfers.Domain.Transfers.TransferAttempt", b =>
                {
                    b.HasOne("Transfers.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Transfers.Domain.Transfers.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
